%%% Generated by music-score %%%
\include "lilypond-book-preamble.ly"
\paper {
  #(define dump-extents #t)

  indent = 0\mm
  line-width = 210\mm - 2.0 * 0.4\in
  ragged-right = ##t
  force-assignment = #""
  line-width = #(- line-width (* mm  3.000000))
}
\header {
  title = ""
  composer = ""
}
\layout {
}

<<
    \new Staff {   \set Staff.instrumentName = "" \set Staff.shortInstrumentName = "" \clef treble \time 4/4 c8-\mf-. g8-. c'8-. g8-. aes8-. ees'8-. d'8-. a'8-. \time 2/4 g'8-. fis'8-. e'8-. d'8-.->
               }
>>