%%% Generated by music-score %%%
\include "lilypond-book-preamble.ly"
\paper {
  #(define dump-extents #t)

  indent = 0\mm
  line-width = 210\mm - 2.0 * 0.4\in
  ragged-right = ##t
  force-assignment = #""
  line-width = #(- line-width (* mm  3.000000))
}
\header {
  title = ""
  composer = ""
}
\layout {
}

<<
    \new Staff {   \set Staff.instrumentName = "" \set Staff.shortInstrumentName = "" \clef treble \time 4/4 \repeat tremolo 8
                                                                                                                             c'16-\mf \repeat tremolo 8
                                                                                                                                                      d'16 \repeat tremolo 8
                                                                                                                                                                           c'16 \repeat tremolo 8
                                                                                                                                                                                                d'16
               }
>>