name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  music-suite-ci:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - run: |
        nix-shell --pure --command "cabal update && ci"
        # nix-build ci.nix --no-out-link --argstr command "CMD"
      shell: bash

  music-suite-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - run: |
        nix-shell --pure --command "cabal update && build-docs"
        cd docs-sphinx
        nix-shell --pure --command "cd docs && make html"
      shell: bash
